# Generated by Django 2.0.3 on 2019-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_special_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_shop',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.ForeignKey(on_delete='CASCADE', related_name='goo_id', to='sadmin.Goods')),
                ('special_id', models.ForeignKey(on_delete='CASCADE', related_name='spc_id', to='sadmin.Special')),
            ],
            options={
                'db_table': 'special_shop',
            },
        ),
    ]
