# Generated by Django 2.0.3 on 2019-05-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_special_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_comment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('give_count', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('user_image', models.CharField(max_length=255)),
                ('user_address', models.CharField(max_length=255)),
                ('user_profession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'special_comment',
            },
        ),
        migrations.CreateModel(
            name='Topic_comment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('Special_comment_id', models.IntegerField()),
                ('anonymity', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'topic_comment',
            },
        ),
    ]
