# Generated by Django 2.0.3 on 2019-05-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_special_comment_topic_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special_comment',
        ),
        migrations.DeleteModel(
            name='Topic_comment',
        ),
    ]
