# Generated by Django 2.0.3 on 2019-05-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_auto_20190515_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourse_detail',
            name='user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
