# Generated by Django 2.0.3 on 2019-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_discourse_detail_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourse_detail',
            name='user_head_image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
