# Generated by Django 2.0.3 on 2019-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0008_auto_20190515_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_comment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('user_head_image', models.CharField(max_length=255)),
                ('user_address', models.CharField(max_length=255)),
                ('user_profession', models.CharField(max_length=255)),
                ('discourse_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('pid', models.IntegerField(default=0)),
                ('evaluate_sum', models.IntegerField(default=0)),
                ('collect_sum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'special_comment',
            },
        ),
    ]
