# Generated by Django 2.0.3 on 2019-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_special_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
