# Generated by Django 2.0.3 on 2019-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0011_auto_20190515_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmsskustock',
            options={'managed': False},
        ),
    ]
